Test if the rule file is readable before trying to egrep it, if it's not exit with an error

diff --git a/src/logcheck b/src/logcheck
--- a/src/logcheck
+++ b/src/logcheck
@@ -22,7 +22,7 @@
 # along with Logcheck; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
-# $Id: logcheck,v 1.132 2006/02/12 04:48:19 jlps-guest Exp $
+# $Id: logcheck,v 1.133 2006/02/12 05:06:27 jlps-guest Exp $
 
 if [ $UID == 0 ]; then
     echo "logcheck should not be run as root. Use su to invoke logcheck:"
@@ -211,10 +211,14 @@ cleanrules() {
 	    rulefile=$(basename $rulefile)
 	    if [ -f ${dir}/${rulefile} ]; then
 		debug "cleanrules: ${dir}/${rulefile}"
-		# pipe to cat on greps to get usable exit status
-		egrep --text -v '^[[:space:]]*$|^#' $dir/$rulefile | cat \
-		    >> $cleaned/$rulefile \
-		    || error "Couldn't append to $cleaned/$rulefile. Disk Full?"
+		if [ -r ${dir}/${rulefile} ]; then
+			# pipe to cat on greps to get usable exit status
+			egrep --text -v '^[[:space:]]*$|^#' $dir/$rulefile | cat \
+		    		>> $cleaned/$rulefile \
+		    	|| error "Couldn't append to $cleaned/$rulefile. Disk Full?"
+		else
+			error "Couldn't read $dir/$rulefile"
+		fi
 	    fi
 	done
     elif [ -f $dir ]; then
