logtail checks, #174173 squashed !

diff --git a/src/logcheck b/src/logcheck
--- a/src/logcheck
+++ b/src/logcheck
@@ -22,7 +22,7 @@
 # along with Logcheck; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
-# $Id: logcheck,v 1.36 2004/05/20 08:09:10 ttroxell Exp $
+# $Id: logcheck,v 1.37 2004/05/20 08:39:46 ttroxell Exp $
 
 
 # Set the umask
@@ -546,16 +546,16 @@ for file in $(egrep --text -v "^#" $LOGFILE); do
 	        # assume the log is rotated by savelog(8)
 		    debug "Running logtail on rotated: $file.0"
 		    $LOGTAIL -f $file.0 -o $offsetfile $LOGTAIL_OPTS > \
-			$TMPDIR/logoutput/$(basename $file) 
-#			|| error "Could not run logtail or save output"
+			$TMPDIR/logoutput/$(basename $file) \
+			|| error "Could not run logtail or save output"
 		    rm -f $offsetfile \
 		        || error "Could not remove $offsetfile"
 		elif [ -e $file.1 ]; then
 		# assume the log is rotated by logrotate(8)
 		    debug "Running logtail on rotated: $file.1"
 		    $LOGTAIL -f $file.1 -o $offsetfile $LOGTAIL_OPTS > \
-			$TMPDIR/logoutput/$(basename $file)
-#			|| error "Could not run logtail or save output"
+			$TMPDIR/logoutput/$(basename $file) \
+			|| error "Could not run logtail or save output"
 		    rm -f $offsetfile \
 		        || error "Could not remove $offsetfile"
 		fi
@@ -563,8 +563,8 @@ for file in $(egrep --text -v "^#" $LOGFILE); do
 	fi
 	debug "Running logtail: $file"
 	$LOGTAIL -f $file -o $offsetfile $LOGTAIL_OPTS \
-	    >> $TMPDIR/logoutput/$(basename $file)
-#	    || error "Could not run logtail or save output"
+	    >> $TMPDIR/logoutput/$(basename $file) \
+	    || error "Could not run logtail or save output"
     else
 	echo "E: File could not be read: $file" >> $TMPDIR/errors \
 	    || error "Could not output to $TMPDIR/errors  Disk Full?"
