enable egrep checks

diff --git a/src/logcheck b/src/logcheck
--- a/src/logcheck
+++ b/src/logcheck
@@ -22,7 +22,7 @@
 # along with Logcheck; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
-# $Id: logcheck,v 1.35 2004/05/19 11:15:21 maks-guest Exp $
+# $Id: logcheck,v 1.36 2004/05/20 08:09:10 ttroxell Exp $
 
 
 # Set the umask
@@ -176,8 +176,9 @@ cleanrules() {
 	    rulefile=$(basename $rulefile)
 	    if [ -f ${dir}/${rulefile} ]; then
 		debug "cleanrules: ${dir}/${rulefile}"
-		egrep --text -v '^\s*$|^#' $dir/$rulefile >> $cleaned/$rulefile
-#		    || error "Could not append to $cleaned/$rulefile.  Disk Full?"
+		# pipe to cat on greps to get usable exit status
+		egrep --text -v '^\s*$|^#' $dir/$rulefile |cat>> $cleaned/$rulefile \
+		    || error "Could not append to $cleaned/$rulefile.  Disk Full?"
 	    fi
 	done
     elif [ -f $dir ]; then
@@ -195,8 +196,8 @@ report() {
 	if [ $SYSLOGSUMMARY -eq 1 ] && [ -x $SYSLOG_SUMMARY ]; then
 	    debug "report: running syslog-summary - $*"
 	    $SYSLOG_SUMMARY $TMPDIR/checked | \
-		egrep -v "^Summarizing " >> $TMPDIR/report 
-#		|| "Could not append to report.  Disk Full?"
+		egrep -v "^Summarizing "|cat >> $TMPDIR/report \
+		    || error "Could not append to report.  Disk Full?"
 	else
 	    if [ $SYSLOGSUMMARY -eq 1 ] && [ ! -x $SYSLOG_SUMMARY ]; then
 	    	debug "report : WARNING : can't exec $SYSLOG_SUMMARY. Running without summary"
@@ -271,7 +272,6 @@ greplogoutput() {
 	if [ ! -f $TMPDIR/checked ]; then
 	    error "Could not output to $TMPDIR/checked.  Disk Full?"
 	fi
-#	    || error "Could not output to $TMPDIR/checked.  Disk Full?"
 
 	if [ -s $TMPDIR/checked ]; then
 	    debug "greplogoutput: Entries in checked"
@@ -292,11 +292,11 @@ greplogoutput() {
 		# Remove any  entries already reported
 		for file in $(ls $raise/ | grep -v logcheck) ; do
 		    debug "Cleaning logcheck: $file"
-		    egrep --text -v -f $raise/$file $TMPDIR/checked \
-			>> $TMPDIR/checked.1 
-#			|| error "Could not output to $TMPDIR/checked.1"
+		    egrep --text -v -f $raise/$file $TMPDIR/checked |cat \
+			>> $TMPDIR/checked.1 \
+			    || error "Could not output to $TMPDIR/checked.1"
 		    mv $TMPDIR/checked.1 $TMPDIR/checked \
-		    || error "Could not move $TMPDIR/checked.1 to \
+		        || error "Could not move $TMPDIR/checked.1 to \
 		    $TMPDIR/checked"
 		done
 	    fi
@@ -336,19 +336,19 @@ cleanchecked() {
 
     if [ -f $clean ]; then 
 	debug "cleanchecked - file: $clean"
-        egrep --text -v -f $clean $TMPDIR/checked >> $TMPDIR/checked.1 
-#	|| error "Could not output to $TMPDIR/checked.1 Disk full?"
+        egrep --text -v -f $clean $TMPDIR/checked |cat >> $TMPDIR/checked.1  \
+	    || error "Could not output to $TMPDIR/checked.1 Disk full?"
 	mv $TMPDIR/checked.1 $TMPDIR/checked \
-	|| error "Could not move $TMPDIR/checked.1 to $TMPDIR/checked"
+	    || error "Could not move $TMPDIR/checked.1 to $TMPDIR/checked"
     elif [ -d $clean ]; then
 	debug "cleanchecked - dir - $clean"
 	for file in $(ls -1 $clean/); do
 	debug "cleanchecked - dir - $clean/$file"
-	    egrep --text -v -f $clean/$file $TMPDIR/checked \
-		>> $TMPDIR/checked.1 
-#		|| error "Could not output to TMPDIR/checked.1 Disk Full?"
+	    egrep --text -v -f $clean/$file $TMPDIR/checked |cat \
+		>> $TMPDIR/checked.1 \
+		    || error "Could not output to TMPDIR/checked.1 Disk Full?"
 	    mv $TMPDIR/checked.1 $TMPDIR/checked \
-	    || error "Could not move $TMPDIR/checked.1 to $TMPDIR/checked"
+	        || error "Could not move $TMPDIR/checked.1 to $TMPDIR/checked"
 	done
     else
 	error "cleanchecked: Not a file or a directory"
@@ -546,10 +546,10 @@ for file in $(egrep --text -v "^#" $LOGFILE); do
 	        # assume the log is rotated by savelog(8)
 		    debug "Running logtail on rotated: $file.0"
 		    $LOGTAIL -f $file.0 -o $offsetfile $LOGTAIL_OPTS > \
-			$TMPDIR/logoutput/$(basename $file)
+			$TMPDIR/logoutput/$(basename $file) 
 #			|| error "Could not run logtail or save output"
 		    rm -f $offsetfile \
-		    || error "Could not remove $offsetfile"
+		        || error "Could not remove $offsetfile"
 		elif [ -e $file.1 ]; then
 		# assume the log is rotated by logrotate(8)
 		    debug "Running logtail on rotated: $file.1"
@@ -557,7 +557,7 @@ for file in $(egrep --text -v "^#" $LOGFILE); do
 			$TMPDIR/logoutput/$(basename $file)
 #			|| error "Could not run logtail or save output"
 		    rm -f $offsetfile \
-		    || error "Could not remove $offsetfile"
+		        || error "Could not remove $offsetfile"
 		fi
 	    fi
 	fi
@@ -567,16 +567,16 @@ for file in $(egrep --text -v "^#" $LOGFILE); do
 #	    || error "Could not run logtail or save output"
     else
 	echo "E: File could not be read: $file" >> $TMPDIR/errors \
-	|| error "Could not output to $TMPDIR/errors  Disk Full?"
+	    || error "Could not output to $TMPDIR/errors  Disk Full?"
     fi
 done 
 
 # first sort the logs to remove duplicate lines (from different logfiles with
 # the same lines) and reduce CPU and memory usage afterwards.
 debug "Sorting logs"
-$SORT -m $TMPDIR/logoutput/* | uniq | sed -e 's/ *$//' \
-    > $TMPDIR/logoutput-sorted 
-#    ||error "Could not output to $TMPDIR/logoutput-sorted Disk Full?"
+$SORT -m $TMPDIR/logoutput/* | uniq | sed -e 's/ *$//' |cat  \
+    > $TMPDIR/logoutput-sorted \
+        ||error "Could not output to $TMPDIR/logoutput-sorted Disk Full?"
  
 
 # See if the tmp file exists and actually has data to check,
