enable header/footer checks

diff --git a/src/logcheck b/src/logcheck
--- a/src/logcheck
+++ b/src/logcheck
@@ -22,7 +22,7 @@
 # along with Logcheck; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
-# $Id: logcheck,v 1.31 2004/05/18 09:07:37 maks-guest Exp $
+# $Id: logcheck,v 1.32 2004/05/19 08:16:45 ttroxell Exp $
 
 
 # Set the umask
@@ -145,11 +145,11 @@ EOF
     exit 1
 }
 
- # Add an identification line at the beginning of the sent mail
+# Add an identification line at the beginning of the sent mail
 setintro() {
     if [ -f /etc/logcheck/header.txt -a -r /etc/logcheck/header.txt ] ; then
-       # This might fail, but the header is not critical
-       $CAT /etc/logcheck/header.txt >> $TMPDIR/report
+       $CAT /etc/logcheck/header.txt >> $TMPDIR/report \
+           || error "Could not append header to $TMPDIR/report  Disk full?"
     fi
 }
 
@@ -157,8 +157,8 @@ setintro() {
 # Add a footer to the report.
 setfooter() {
     if [ -f /etc/logcheck/footer.txt -a -r /etc/logcheck/footer.txt ] ; then
-       # This might fail, but the footer is not critical
-       $CAT /etc/logcheck/footer.txt >> $TMPDIR/report
+       $CAT /etc/logcheck/footer.txt >> $TMPDIR/report \
+           || error "Could not append footer to $TMPDIR/report Disk full?"
     fi
 }
 
